networks:
    vpnbox:                        # separated network for vpnbox container, recommended
        driver: bridge
        driver_opts:
            com.docker.network.bridge.gateway_mode_ipv4: routed
            com.docker.network.bridge.enable_ip_masquerade: 0
        name: vpnbox
        ipam:
            config:
                - subnet: 172.31.254.248/30
                  gateway: 172.31.254.249

    lan:                           # interface bridged to your LAN, useful if you need RIPv2 routing
        driver: macvlan
        driver_opts:
            parent: bond0          # host interface bridged to the LAN
        ipam:
            config:
                - subnet: 192.168.10.0/24
                  gateway: 192.168.10.1

services:
    vpnbox:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: vpnbox
        privileged: true
        restart: always
        networks:
            vpnbox:
                ipv4_address: 172.31.254.250
            lan:
                ipv4_address: 192.168.10.200  # adjust to a free IP on your LAN
        dns:
            - 127.0.0.1
        volumes:
            - ./data/:/data                   # where vpnbox data (configs, logs, etc.) live
        ports:
            #- "3100:3100"                    # web ui
            #- "3128:3128"                    # squid proxy
            #- "1080:1080"                    # socks proxy
            #- "22:22"                        # ssh tunnels
            #- "53:53/udp"                    # dns server
