client
proto tcp
resolv-retry infinite
nobind
persist-key
persist-tun
auth-user-pass
verb 3
cipher AES-256-GCM
auth SHA256
data-ciphers AES-256-GCM:AES-128-GCM
fast-io
pull
route-delay 2
redirect-gateway

