[include]
files = /data/supervisor.d/*.conf

[unix_http_server]
file=/var/run/supervisor.sock
chmod=0700

[supervisord]
logfile=/dev/stdout
logfile_maxbytes=0
pidfile=/var/run/supervisord.pid
childlogdir=/var/log

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[program:squid]
command         = /usr/sbin/squid -f /etc/squid.conf -N
redirect_stderr = true
priority        = 600
startretries    = 10
autorestart	= true

[program:danted]
command         = /usr/sbin/danted -f /etc/danted.conf
redirect_stderr = true
startretries    = 10
autorestart     = true

[program:sshd]
command         = /usr/sbin/sshd -D -e
redirect_stderr = true
startretries    = 10
autorestart     = true

[program:dnsmasq]
command         = /usr/sbin/dnsmasq -k -x /run/dnsmasq/dnsmasq.pid -u dnsmasq -r /run/dnsmasq/resolv.conf
redirect_stderr = true
startretries    = 10
autorestart     = true

[program:bird]
command         = /usr/sbin/bird -f -u bird -g bird -P /var/run/bird/bird.pid -s /var/run/bird/bird.ctl
redirect_stderr = true
startretries    = 10
autorestart     = true

[program:charon]
command         = /usr/sbin/charon-systemd
redirect_stderr = true
priority        = 100
startretries    = 10
autorestart     = true

[program:web]
command         = /usr/bin/python3 /usr/local/routehouse/bin/web.py
redirect_stderr = true
startretries    = 5
autorestart     = true
